### PR TITLE
Prefer to not clobber duplicates

### PR DESCRIPTION
**Pull request by cjsheets**
Nice, clean implementation!

I think it would be improved if duplicate values weren't lost while sorting.

### CODE REVIEW

**Comment by cjsheets** [comment]
My proposal isn't enough, you have to account for the <= matching the pivot

**Comment by kutyel** [comment]
Hi! Thanks for the PR but I don’t see the benefit of this change :)

**Comment by cjsheets** [comment]
No Problem. Just FYI, the problem is the algorithm will loose duplicate values.

What should happen: [ 2, 0, 2, 4, 3, 2, 1 ] => [0, 1, 2, 2, 2, 3, 4]

What happens as written: [ 2, 0, 2, 4, 3, 2, 1 ] => [0, 1, 2, 3, 4]

It's a considerable issue. The sorted array shouldn't be shorter than the unsorted array.

**Comment by kutyel** [comment]
Wow I didn't notice that, thanks for telling! Maybe it would be worth telling [this](https://illustrated-algorithms.now.sh/quicksort) guys as well :)

**Pull request closed without merging**
